# Operasi Matematika & Numpy
Sebelum lanjut, harap:
1. Jika menggunakan jupyter, silahkan pilih "File" --> "Download" --> "Download .ipynb"
2. Jika menggunakan colab, silahkan pilih "File" --> "Save a copy in drive"

In [ ]:
import numpy as np

### Pengenalan array

In [ ]:
#1D array
a = np.array([3, 1, 5, 6,3,1])
print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  6
dimensi array =  1
ukuran array =  (6,)


In [ ]:
#Slicing
a[:4]

array([3, 1, 5, 6])

In [ ]:
print('a[1:3] = ', a[1:3])
print('a[:3] = ', a[:3])

a[1:3] =  [1 5]
a[:3] =  [3 1 5]


In [ ]:
#2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print('entry ke-1 & 2 baris ke-3 = ', A[2,:2])
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

entry ke-1 & 2 baris ke-3 =  [7 8]
entry ke-2 & 3 kolom ke-3 =  [6 9]


###Latihan-2 (2D array)

In [ ]:
#Lengkapi kodingan berikut
print('banyaknya entry = ', np.size(A) )
print('dimensi array = ', np.ndim(A))
print('ukuran array = ', np.shape(A))

banyaknya entry =  9
dimensi array =  2
ukuran array =  (3, 3)


In [ ]:
#Slicing
print('baris ke-2 = ', A[1])
print('entry ke-2 & 3 baris ke-2 = ', A[1, 1:])
print('entry pertama & 2 kolom ke-2 = ', A[:2, 1])

baris ke-2 =  [4 5 6]
entry ke-2 & 3 baris ke-2 =  [5 6]
entry pertama & 2 kolom ke-2 =  [2 5]


###Latihan-3 (Slicing)

In [ ]:
#Lengkapi kodingan berikut
print('baris ke-3 = ', A[2] )
print('entry ke-1 & 2 baris ke-3 = ',A[2,1:3] )
print('entry ke-2 & 3 kolom ke-3 = ', A[1:,2])

baris ke-3 =  [7 8 9]
entry ke-1 & 2 baris ke-3 =  [8 9]
entry ke-2 & 3 kolom ke-3 =  [6 9]


output jawaban:
baris ke-3 =  [7 8 9]

entry ke-1 & 2 baris ke-3 =  [7 8]

entry ke-2 & 3 kolom ke-3 =  [6 9]

### Operasi Matematika di Numpy

In [ ]:
C = A*A
print('perkalian antar entry = ')
print(C)

perkalian antar entry = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
B = np.array([[1,2,1], [2, 1, 1], [3, 4, 1]])

In [ ]:
print(B)

[[1 2 1]
 [2 1 1]
 [3 4 1]]


In [ ]:
print('perkalian matriks = ')
print(np.matmul(A,B))

perkalian matriks = 
[[14 16  6]
 [32 37 15]
 [50 58 24]]


Bisa dilihat perbedaan perkalian antar entry dan perkalian matriks biasa?

In [ ]:
print('determinan matriks A = ', np.linalg.det(A))
print('determinan matriks B = ', np.linalg.det(B))
print('determinan matriks C = ', np.linalg.det(C))

determinan matriks A =  0.0
determinan matriks B =  4.000000000000001
determinan matriks C =  -216.00000000000006


In [ ]:
print('nilai dan vektor eigen matriks A = ', np.linalg.eig(A))

nilai dan vektor eigen matriks A =  (array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [ ]:
print('nilai eigen matriks A = ', np.linalg.eig(A)[0])

nilai eigen matriks A =  [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [ ]:
print('vektor eigen matriks A = ', np.linalg.eig(A)[1])

vektor eigen matriks A =  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
e_vec = np.linalg.eig(A)[1][:, 0] #Menagambil eigen vector pertama ([-0.23197, -0.52532209, -0.8186735  ])
e_val = np.linalg.eig(A)[0][0] #Mengambil eigen value pertama (1.61168440e+01)

In [ ]:
print(np.matmul(A, e_vec)) #hasil A * eigen vector

[ -3.73863537  -8.46653421 -13.19443305]


In [ ]:
print(e_val*e_vec) #hasil eigen value * eigen vector (Hasilnya sama)

[ -3.73863537  -8.46653421 -13.19443305]


### Latihan-4 (Operasi matriks)

In [ ]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B







In [ ]:
#Ketik Kode disini
no1 = 2*A
no2 = 2+A
no3 = A+B
no4 = A-B
no5 = np.linalg.det(A)
D = np.linalg.inv(B)
no7 = np.transpose(D)
eigenA = np.linalg.eig(A)
eigenB = np.linalg.eig(B)

In [ ]:
print(eigenB)

(array([1.8074176, 7.1925824]), array([[-0.97271381, -0.76626443],
       [ 0.23200828, -0.64252535]]))


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)? 

In [ ]:
#Tunjukkan bedanya di kodingan di bawah ini
per_entry = A*B
per_matriks = np.matmul(A,B)
print(per_entry)
print(per_matriks)

[[ 3 10]
 [ 7 48]]
[[ 5 17]
 [29 83]]


output jawaban: 

perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308,  1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]]
